### ISSUE TITLE
Install fails for Stephen, but hijacking with Nathaniel's setup works

### ISSUE THREAD

**Issue by nvkelso** [whosonfirst/py-mapzen-whosonfirst-api#2]
See: 

- https://gist.github.com/nvkelso/a34e9bdb3944ca6cd5596dabce41b263

Possibly related to Nathaniel using `bash` and Stephen using `zsh`???

**Comment by stepps00** [comment]
Hit this error again on a playground Ubuntu machine. Applying the same fix worked.

**Comment by thisisaaronland** [comment]
Can someone paste the error message in question? @dphiffer is the resident `zsh` enthusiast

**Comment by stepps00** [comment]
Looks like this is affecting Nathaniel's installs after all. Here is the error message, when trying to run the `csv-to-feature-collection` script from the `py-mapzen-whosonfirst-utils` repo:

```
python wof-csv-to-feature-collection -p /usr/local/mapzen/whosonfirst-data/data -c /Users/nathanieldouglass/Desktop/poly_countries.csv -o /Users/nathanieldouglass/Desktop/WOF_Countries.geojson full -i
Error processing line 3 of /Library/Python/2.7/site-packages/mapzen.whosonfirst.api-0.322-py2.7-nspkg.pth:

  Traceback (most recent call last):
    File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site.py", line 152, in addpackage
      exec line
    File "<string>", line 1, in <module>
  KeyError: 'mapzen.whosonfirst'

Remainder of file ignored
```

**Comment by stepps00** [comment]
(Applying the same fix worked on his machine as well)

**Comment by thisisaaronland** [comment]
Yeah, okay. I am starting to think that it's a namespacing issue and that we will either need to bundle the API package with `py-mapzen-whosonfirst` or just give it a different name.

Thanks, Guido...
